parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ProductsServiceClient:
        arguments:
            $baseUrl: '%env(default::PRODUCTS_SERVICE_URL)%'
