parameters:
    user_service_base_url: "%env(USER_SERVICE_BASE_URL)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\Service\UserServiceClient:
        arguments:
            $userServiceBaseUrl: "%user_service_base_url%"
